_base_: ../base.yaml

trainer:
  callbacks:
    - ${snipets.callbacks.model_checkpoint}
    - ${snipets.callbacks.visualizer_callback}
    - ${snipets.callbacks.exponential_warmup_annealer}

datamodule:
  train_dataset_fn_dict:
    strong: ${snipets.datasets.train.strong}
    weak: ${snipets.datasets.train.weak}
    unsup: ${snipets.datasets.train.unsup}

task:
  _target_: m3l.audio.sed.tasks.weak_ema_sed_task.WeakEMASEDTask

  model:
    _target_: m3l.audio.sed.models.strong_weak_model.StrongWeakSEDModel
    encoder:
      _target_: m3l.audio.common.encoders.dcase_crnn.CRNN
      dim_emb: 768

    strong_head:
      _target_: m3l.audio.sed.heads.linear_head.LinearHead
      n_channels: 256
      n_class: ${n_class}
    
    weak_head:
      _target_: m3l.audio.sed.heads.attention_head.AttentionHead
      n_channels: 256
      n_class: ${n_class}

  freezed_model:
    _target_: m3l.audio.common.encoders.beats.BEATsModel
    checkpoint_path: ${oc.env:BEATS_CKPT_PATH}/BEATs_iter3_plus_AS2M.pt
